### ISSUE TITLE
Question à propos de la configuration

### ISSUE THREAD

**Issue by chatainsim** [Thilas/plex-betaseries-webhook#69]
Bonjour,
J'ai une question à propos de la valeur de SERVER_URL.
Je ne vois pas à quoi elle correspond.
Est-ce l'URL donné sur betaserie a coller dans le webhook de Plex ?
Merci

**Comment by Thilas** [comment]
Bonjour,
Comme indiqué dans la liste des [paramètres](https://github.com/Thilas/plex-betaseries-webhook#parameters), `SERVER_URL` sert à spécifier l'url publique qui sera utilisée pour accéder au webhook depuis Plex. A noter que cette url doit être en https pour que l'authentification auprès de Betaseries fonctionne.
L'url que vous mentionnez me semble être tout autre chose: Betaseries propose une intégration avec Plex et fournit une url vers leur propre webhook. Pour autant que je me souvienne, ce webhook fait la même chose que le mien en ce qui concerne les séries mais ne gère pas les films. Du moins c'était le cas à l'époque où je l'avais testé.
Bref, soit vous utilisez le webhook natif de Betaseries pour Plex, soit vous utilisez celui implémenté dans ce projet. Dans ce cas, vous devrez hébergé le service quelque part accessible via une url en https et qui doit être renseignée dans le paramètre `SERVER_URL`.
En espérant que ça vous aide.

**Comment by chatainsim** [comment]
Bonjour,
Merci pour cette réponse, en fait je pensais que ça permettait de se passer du webhook Plex.
C'est pour ça que je ne comprenais pas à quoi correspondait ce paramètre.
